"""Regenerate the committed report for the bundled example set.

The report is committed so that anyone reading the repository sees the real
output before deciding whether to install anything. A screenshot would go
stale silently; a file that a test compares against cannot.

    python scripts/refresh_example_report.py

Run it after changing the lexicon, the checks or the report layout. The
build fails until you do, which is the point.
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from audit_readiness_ledger.documents import load_directory  # noqa: E402
from audit_readiness_ledger.hygiene import (  # noqa: E402
    check_cross_references,
    check_document,
)
from audit_readiness_ledger.lexicon_loader import (  # noqa: E402
    load_framework,
    load_signatures,
)
from audit_readiness_ledger.report import Analysis, render_markdown  # noqa: E402
from audit_readiness_ledger.signatures import evaluate_all  # noqa: E402

EXAMPLES = ROOT / "examples" / "meltemi-logistics"
DOCUMENTS = EXAMPLES / "documents"
REPORT = EXAMPLES / "example-report.md"

# Exactly the path the README tells people to run, so the committed report
# is the one they get rather than a near miss.
SOURCE = "examples/meltemi-logistics/documents"

# Pinned so the committed report does not change every day for no reason.
# It sits after every approval date in the set, and after one review date.
RUN_DATE = date(2026, 8, 10)


def analyse() -> Analysis:
    loaded = load_directory(DOCUMENTS)
    framework = load_framework("iso-27001-2022")
    signatures = load_signatures("iso-27001-2022", framework)
    documents = list(loaded.documents)
    return Analysis(
        framework=framework,
        findings=tuple(evaluate_all(framework.ids, signatures, documents)),
        hygiene=tuple(f for d in documents for f in check_document(d, RUN_DATE)),
        cross_references=tuple(check_cross_references(documents)),
        documents_read=tuple(d.name for d in documents),
        units=loaded.units,
        skipped=loaded.skipped,
        source=SOURCE,
        run_date=RUN_DATE,
    )


def build() -> str:
    header = (
        "<!-- Generated by scripts/refresh_example_report.py. Do not edit by hand. -->\n"
        "<!-- Meltemi Logistics is fictional. See README.md in this folder. -->\n\n"
    )
    return header + render_markdown(analyse())


if __name__ == "__main__":
    REPORT.write_text(build(), encoding="utf-8")
    print(f"wrote {REPORT.relative_to(ROOT)}")
